# Generated by Django 2.2.13 on 2020-07-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_delete_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Information',
        ),
    ]
