# Generated by Django 2.2.13 on 2020-07-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200704_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Information',
            new_name='Project',
        ),
    ]
