# Generated by Django 2.2.13 on 2020-07-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200704_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_str',
            field=models.CharField(default='erics-work', max_length=255),
        ),
    ]
