# Generated by Django 3.0.8 on 2020-07-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_url_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body_html',
            field=models.TextField(default=''),
        ),
    ]
