# Generated by Django 3.0.8 on 2020-07-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_body_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='snippet',
            field=models.TextField(default=''),
        ),
    ]
