# Generated by Django 3.0.8 on 2020-07-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(default='<i class="icon-screen-smartphone text-primary"></i>', max_length=255),
        ),
    ]
